<? include "gzheader.php";
include "scripts/vsys.php";
?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE><? echo $conf["sitename"]; ?> :: Help</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<LINK href="css/common.css" type=text/css rel=stylesheet>

<SCRIPT language=javascript type=text/javascript>
		<!--
		function checkCR(evt) {
		var evt = (evt) ? evt : ((event) ? event : null);
		var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
		if ((evt.keyCode == 13) && (node.type=="text")) {return false;}
		}
		document.onkeypress = checkCR;
		//-->
		</SCRIPT>

<META content="MSHTML 5.50.4522.1800" name=GENERATOR></HEAD>
<BODY text=#ffffff bgColor=#000000 leftMargin=0 topMargin=0 marginheight="0" 
marginwidth="0">
<?
include "top.php";
?>
<TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
  <TBODY>
  <TR>
    <TD class=menu_cell_repeater style="PADDING-LEFT: 15px" vAlign=top width=140>
	<?
include "left.php";
?>
	</TD>
      <TD style="PADDING-RIGHT: 15px; PADDING-LEFT: 15px; PADDING-TOP: 12px" 
    vAlign=top align=left> <BR>
      <H1>User Guide </H1>
      <UL>
        <LI><A href="help.php#Gameplay">Gameplay</A> 
        <BR>
        <LI><A href="help.php#rules">Rules</A> <BR>
        <LI><A href="help.php#FAQ">Frequently Asked 
        Questions</A> <BR>
        <LI><A 
        href="help.php#Interface">Interface</A> 
        <UL>
          <LI><A 
          href="help.php#Command_Center">Command 
          Center</A> 
          <LI><A href="help.php#Attack">Attack</A> 
          <LI><A href="help.php#Attack_Log">Attack 
          Log</A> 
          <LI><A href="help.php#Armory">Armory</A> 
          <LI><A 
          href="help.php#Training">Training</A> 
	  <LI><A 
          href="help.php#Upgrade">Upgrades</A> 
          <LI><A 
          href="help.php#Intelligence">Intelligence</A> 

          <LI><A 
          href="help.php#Mercenaries">Mercenaries</A> 

          <LI><A href="help.php#Logout">Logout</A> 
          <LI><A 
          href="help.php#Messages">Messages</A> 
        </LI></UL><BR>
        <LI><A href="help.php#Glossary">Glossary</A> 
        </LI></UL> <A name=Gameplay></A>
      <H2>Gameplay </H2>
      <P>In World War 2, you are in command of an army of either the United States, 
      United Kingdom, Germany or Japanese. The aim of the game is to achieve the highest 
      overall ranking - worked out by taking a combination of your attack, 
      defence, covert (spy), and retaliaion rankings - whoever has the lowest combined 
      ranking will be 1st in the overall rankings. This makes it important to 
      keep your army evenly balanced in all these areas. </P>
      <P>To build up your attack and defence strength, you can (a) recruit and 
      train soldiers, (b) hire mercenaries, and (c) buy weaponry. To recruit 
      soldiers you must have people click on your unique link (you can find this 
      in your <A 
      href="help.php#Command_Center">Command 
      Center</A>). Each time you recruit an additional 10 soldiers, your attack and 
      defence strength will increase slightly, as will the amount of gold you 
      receive per turn. </P>
      <P>In addition to those soldiers generated by unique link clicks, once a 
      turn you will recruit a number of soldiers determined by your current 'unit 
      production' value. This value can be upgraded on the <A 
      href="help.php#Upgrade">Upgrade</A> page. 
      </P>
      <P>To train your soldiers, you use the <A 
      href="help.php#Training">Training</A> page. 
      Soldiers can be trained to be specialists in either attack or defence - 
      whichever you choose, they will boost that ranking further, while ceasing 
      to contribute to the other ranking. You can also train soldiers to become 
      spies or special forces operatives, which will be discussed in more detail later. In this case they 
      cease to contribute to your attack/defence strength and the amount of gold 
      you get per turn, as instead they are being kept in readiness for any 
      covert missions you may choose to send them on or fight back when you get attacked. </P>
      <P>You can hire mercenaries on the <A 
      href="help.php#Mercenaries">Mercenaries</A> 
      page, but only up to a strength of 25% of your total force - so for every 
      3 normal soldiers you gain, you can hire one more mercenary. Mercenaries 
      contribute to your attack or defence strength, but do not contribute to 
      the amount of gold you gain each turn. Mercenaries are also 50% more affective
       than trained soldiers <b>IF</b> they are holding weapons.  </P>
      <P>Weaponry can be purchased (and repaired, sold or scrapped) on the <A 
      href="help.php#Armory">Armory</A> page. There 
      are various weapons available for both attacking and defending, becoming 
      increasingly expensive as they become more effective. The exact strength 
      of each weapon in your armory is dependent upon both its state of repair 
      (weapons become damaged during battles and must be repaired to remain 
      fully effective), and also your level of siege technology and 
      fortifications. Higher levels of siege technology and fortifications raise 
      the strength of every single weapon you possess, so they are well worth 
      upgrading. </P>
      <P>Your other ranking, Covert Action, can be raised in two ways. The first 
      is to train spies as mentioned earlier. Every spy you train increases your 
      covert strength, and therefore helps you move up the covert ranking. The 
      other way to increase your covert strength is to upgrade the skill level 
      of your spies.Training of spies can be 
      done on the <A 
      href="help.php#Training">Training</A> page. 
       Upgrading covert skill level can be 
      done on the <A 
      href="help.php#Upgrade">Upgrade</A> page. 
      </P>
      <P>Each race/country in World War 2 has a particular area in which they excel. 
      These can work to your advantage in gaining higher rankings, so it is 
      worth considering them before choosing your race: </P>
      <UL>
        <LI><B>United States (USA)</B> earn 25% more gold each turn than the other three 
        races. This can be used to buy more weaponry or train more soldiers. 
<BR>
        <LI><B>Japanese</B> are 25% better at covert action than any other race. 
        This can be a great advantage when spying on other 
        people's armies. <BR>
        <LI><B>Germans</B> attack with 25% more strength than the other races. The 
        advantages to this are obvious, giving you a much better chance of 
        defeating other armies in combat. <BR>
        <LI><B>The United Kingdom (UK)</B> are 25% stronger at defending than any other race. 
        This makes it more likely that they will withstand enemy attacks, 
        enabling them to keep their gold for themselves. </LI></UL>
      <P>If you are ready to start playing as commander of your own army, then 
      <A href="register.php">click here to create an 
      account</A>. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><BR>&nbsp; <A 
      name=rules></A>
      <H2>Rules </H2><br>
      <small>There are two offical languages in World War 2: English and Portuguese. (A multilingual version is comming soon)</small>
      <P>
      <P><b>These rules can be changed at ANY time.</b><BR>Please keep in mind that all 
      accounts are closely monitored, and we do catch the cheaters. 
      <P><STRONG>Legal: </STRONG>
      <LI>Clicking on your own link once per <? echo $conf["hours_to_block_same_user_recruiting"]; ?> Hours 
      <LI>Clicking on your officers' links once per <? echo $conf["hours_to_block_same_user_recruiting"]; ?> Hours 
      <LI>Clicking ANY OTHER link once per <? echo $conf["hours_to_block_same_user_recruiting"]; ?> Hours
      <LI>Posting your link on message boards where it is allowed and is 
      on-topic. 
      <LI>Emailing your link to your friends or sending it to them on instant 
      messenger. 
      <LI>Having people click your link more than once (but not within <? echo $conf["hours_to_block_same_user_recruiting"]; ?> hours) 
      . 
      <LI>Having an Alliance of WW2 players. 
      <LI>Having your link in your AIM/MSN/ICQ etc. profile. 
      <LI>Posting your link on a personal website.
      <LI>Logging OUT OF an account. Yes this is legal, it's necessary to get onto your account.
      <P><BR><STRONG>Illegal: </STRONG></P>            
      <LI>Attempting to Hack/Packet the server or Abusing security holes (if 
      any). 
      <LI>ONLY ONE ACCOUNT per person. Having more than one account because you 
      have more than one computer or because a friend registered an account and 
      gave it to you is cheating. 
      <LI>Sharing passwords with other people and logging into accounts that are 
      not yours.
      <LI>Navigating in other peoples accounts. Just because someone logged in for you,
      	Or their password was saved in a browser doesn't mean that it's not cheating. 
      <LI>Posting your link in chat rooms, newsgroups, message boards, or forums 
      unless it is <B>explicitly</B> allowed by the owner/operator of the chat 
      room, newsgroup, message board, forum, etc.. 
      <LI>E-mailing your link to people whom you do not know, or to e-mail lists 
      or "reflectors". 
      <LI>Posting your link on a forum where it is against that forum's policies 
      or off-topic 
      <LI>Repeatedly refreshing pages to slow the server. 
      <LI>Registering an email address that is not yours. 
      <LI>Registering multiple accounts. 
      <LI>Advertising your link on adult sites. 
      <LI>Advertising other sites
      <LI>Sending your link to people you do not know. 
      <LI>Sending the link to an e-mail reflector or USENET group. 
      <LI>Putting your link in popup windowss, inside any frame, or using 
      redirects. 
      <LI>Using a script/program or ANY AUTOMATED PROCESS to automatically gain 
      recruits. 
      <LI>Using proxy IPs/Addresses/servers for anything. 
      <LI>Having an AUTOMATED PROCESS to repeatedly request pages on the server.
      <li>Accessing this website through the intelligence of a NON-HUMAN DEVICE.
      <li>AUTOMATED buying/attacking/messaging/logins/macros are NOT allowed.      
      <LI>Using scripts/programs that fetch information off the WW2 website. 
      <LI>Signing up with false email addresses. 
      <li>"Sell offs"/"feeding" or collaborated attacking is not allowed.
      <li>A cheat in this game is condsidered someone who gains an unfair advantage over other players, by any means.
      <P><STRONG>Enforcement:</STRONG> </P>
      <LI>If you are caught doing any of the above, your account will either be 
      suspended or terminated. 
      <LI>If you get caught trying to Hack/Packet or Abuse the server, you will 
      be banned and your ISP will be contacted. Be warned! 
      <P></P>
      <P></P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><BR>&nbsp; <A 
      name=FAQ></A>
      <H2>Frequently Asked Questions </H2>
      <P><B>What are the siege and fortification levels?</B> <BR>We'd rather not 
      say, and let you find out on your own =) <BR></P>
      <P><B>What are the covert and retaliaion levels?</B> <BR>We'd rather not 
      say, and let you find out on your own <BR></P>
      <P><B>What happened to all my stuff?</B> <BR>A new round has begun - your 
      weaponry and army size have been reset, as have everyone else's. Now is 
      the time to rebuild and prove yourself better than those around you! </P>
      <P><B>Why am I losing gold and soldiers?</B> <BR>You are probably being 
      attacked. Check your attack log to see who attacked you, how many soldiers 
      they killed and how much gold they stole from you. </P>
      <P><B>How come I'm not listed in the rankings?</B> <BR>Ranks are only 
      recalculated once every turn, so you will have to wait until rankings are 
      generated to appear on the rankings page. </P>
      <P><B>Why doesn't my rank improve when I get more weapons?</B> <BR>Ranks 
      are only recalculated once every turn, so you will have to wait to see how 
      your ranking has been changed by upgrades or purchases. </P>
      <P><B>How much does this cost to play?</B> <BR>Nothing. It's free. Enjoy! 
      </P>
      <P><B>Why can't I/my friends view the recruit page?</B> <BR>Many AOL users 
      cannot view our pages properly. We're sorry about the problem, and are 
      looking into possible solutions. Until then, we recommend the <A 
      href="http://www.mozilla.org/products/firebird/">Mozilla Firebird</A> web 
      browser. </P>
      <P><B>My account was suspended. Why?</B> <BR>Probably because you violated 
      the rules, most likely spamming on IRC. When you login, it should tell you 
      the reason you were suspended. Your account will automatically be 
      unsuspended within 3 days. If you feel you have been unjustly suspended or deleted
      please email the admin(s)</P>
      <P><B>It's hard to get people to click my link. Is there another way to 
      gain recruits?</B> <BR>The easiest way to gain recruits is to persuade 
      friends to click your link, but you can also upgrade your Unit Production 
      (on the Upgrade page), and hire mercenaries to boost your army strength. 
      </P>
      <P><B>Why don't I ever kill any enemy soldiers?</B> <BR>The bigger your 
      army, the more casualties you are likely to suffer. Armies small enough 
      will not usually suffer casualties because this would hurt the army much 
      more. </P>
      <P><B>How do I change my race/country?</B> <BR>There is a link at the bottom of your
       command center where you can change you race/country. Changing your race/country resets your account
       and you lose all your stats. You can purchase a race/country change without penalty at the forum.
       </P>
      <P><B>I forgot my password, what should I do?</B> <BR>Go to <A 
      href="forgotpass.php">this page</A> and you 
      can get your password emailed to you. </P><!-- 
<p>		<b></b>
<br />	
</p>
<p>		<b></b>
<br />	
</p>
<p>		<b></b>
<br />	
</p>
 -->
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><BR>&nbsp; <A 
      name=Interface></A>
      <H2>Interface </H2>
      <P>At the top of every page, around the main logo, are links to: </P>
      <UL>
        <LI>the World War 2 homepage (which will display any news 
        announcements from the site admins), 
        <LI>the WW2 forums, 
        <LI>the main rankings page for the current Round, 
        
        <LI>the Help and About Us pages, for further info about WW2. </LI></UL>
      <P>On the left of every page you will find the menu, or if you aren't 
      logged in yet you will see the Login box. If you are not logged in, enter 
      your username and password here to gain access to the other areas of the 
      site. If you do not yet have a username and password, then click on the 
      'Register' link in the Login box to create a new account. </P>
      <P>Once you have logged in and can view the main menu, you will have 
      access to the areas of the site described below. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Command_Center></A>
      <H3>Command Center </H3>
      <P>The Command Center contains a synopsis of all the information about 
      your army, including your overall rank and your attack, defence and covert 
      rankings. It also shows your strength in each area, how much gold you 
      should receive at the start of the next turn, information about army size 
      and disposition, lists your officers, and shows you your unique link which 
      you can use for recruiting. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Attack></A>
      <H3>Attack </H3>
      <P>The Attack page is a listing of all the players currently taking part 
      in the game. It starts off on the page of players whose rank is close to 
      your own (you can see your own position on this page, your name shows up 
      in bold text). Using the Next and Previous links at the bottom of the 
      page, you can move up and down the rankings looking for suitable armies to 
      attack. To find out more about any army, click on that player's name. </P>
      <P>This will give you their stats page, showing their army size, how much 
      gold they have if you can see it, and various other info. At the bottom of this page are two 
      buttons, allowing you to either Send a Message to this player using the 
      built-in <A 
      href="help.php#Messages">messaging</A> system, 
      or to Attack them to try and take their gold. </P>
      <P>If you choose to Attack the player, you will be taken to another page 
      which allows you to select various types of attack (including covert 
      missions, (reconnaisance) ), and other details about your 
      planned attack. </P>
      <P>If you are planning a normal attack, you will have to specify how many 
      attack turns you wish to use - you can see how many you have available at 
      the top of this page. The more turns you use on one attack mission, the 
      more gold you will take if your attack is successful - however, you will 
      also sustain more casualties and weapon damage when using higher numbers 
      of attack turns.  </P>
      <P>If you are planning a covert mission, you will have to specify how many 
      spies to send. If your covert strength is close to the player you are trying to spy on
      you may experience "disinformation" where some of the players details may be falsified, there is know
      way of you know this though, so never trust your spy logs completely. Sending more spies increases your chance of
      getting information (not necessary correct information) but increases the likelyhood of the spies getting caught and killed,
      whereas sending only one or two spies decreases your chance of getting information but increases the chances of your spies
      returning for another covert mission. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Attack_Log></A>
      <H3>Attack Log </H3>
      <P>Your attack log is divided into two parts - people who have attacked 
      you, and people you have attacked. Each part shows the <?=$conf["users_per_page_on_attack_log"] ?> most recent 
      attacks, with next/previous links for changing the view to show older 
      attacks. Next to the basic details about each attack is a link to the full 
      battle report, which will give more detailed information about that 
      particular battle. Entries in the attack log will be deleted after <?=$conf["days_to_hold_logs"] ?> days. 
      </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Armory></A>
      <H3>Armory </H3>
      <P>In the Armory you will see a list of your current weaponry, along with 
      buttons enabling you to repair it if damaged, check it for sabotage, and 
      scrap or sell it. Underneath that is a list of all available weaponry for 
      your army, which you can purchase items from if you have sufficient gold. 
       </P>
      <P>Repairing damaged weapons is done on a per-weapon-type basis. Damage is 
      shown as an average of how many points of strength each weapon of that 
      type has lost. You choose how many points to repair (on all weapons of 
      that type simultaneously), and then click the button (which will be 
      showing you the cost per point). Note that sometimes when you buy new 
      weaponry, the average damage shown will fall, as the new item will be at 
      full strength, thereby reducing the average damage across all the weapons 
      of that type. </P>
      <P>If your weapons are above 60% strength, you have the option to sell 
      them back to the armory for an amount of money based on their state of 
      repair. If they are undamaged, then you will receive 70% of the amount you 
      paid for them originally. If your weapons fall beneath 60% repair, you are 
      instead given the option to scrap them - this will enable you to discard 
      largely ineffective weaponry and start again with new, healthy items. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Training></A>
      <H3>Training </H3>
      <P>On the training page you can see details of your troops, as well as 
      training troops as attack or defence experts, as spies or as special forces operatives. You can also 
      remove attack/defence training, to allow you to reallocate troops from one 
      category to the other. You cannot reallocate spies or special forces operatives. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Upgrade></A>
      <H3>Upgrades </H3>
      <P>On the Upgrades page are the upgrade areas for spy level, unit 
      production, sheilding technology, weapons technology, special forces level,
       max officer limit and bank deposit percentage.
        Increasing your spy level will give you a better chance of 
      successfully spying on  other players, and will help to 
      protect you from other players who attempt to spy on o you. 
      Upgrading your unit production will increase the number of men you recruit 
      automatically once per day.
      Upgrading sheilding technology increases your defence, whereas upgrading your weapon technology increases your attack strength.
      Upgrading your special forces level increases your retaliaion against other players.
      Increasing of the max officer limit allows you to have more officers (this is not reset at the end of a round).
      Increasing the level of bank deposit percentage lowers the amount taken off you when you deposit in the bank.</P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Intelligence></A>
      <H3>Intelligence </H3>
      <P>The intelligence page contains two lists of information. The first is a 
      list of any covert missions <I>into</I> your camp, which your own spies 
      intercepted. This may allow you to work out who has been spying on you or 
      sabotaging you, if some of their missions failed. </P>
      <P>The second list of information is the people you have spied on.
       Here you will see the number of covert missions you have 
      launched against each person, with a link to a page containing the 
      detailed report from each mission. Covert mission are deleted from your 
      intelligence logs after <?=$conf["days_to_hold_logs"] ?> days. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Mercenaries></A>
      <H3>Mercenaries </H3>
      <P>On this page you can see the details of your current troops, and you 
      can hire mercenaries. Mercenaries can be hired as attack specialists, 
      defence specialists, or all-purpose troops. Once hired, they cannot be 
      retrained. Mercenaries cannot be spies, and do not contribute to the 
      amount of gold you receive each turn, but they do boost your attack and/or 
      defence strength (depending on what type of training they have). 
      Mercenaries become available for hire at the start of each turn, but their 
      numbers are limited and so there are often none available shortly after 
      that. You can only have 25% of your army consisting of mercenaries. 
      Mercenaries are 50% strong than regular trained soldiers when they are holding weapons, but if they are not
      holding weapons they are as strong as an untrained soldier without a weapon. There is a limit, however, to 
      how many mercenaries you can have holding weapons: weapons are first distributed to trained solders then mercenaries; but only 1 mercenary per 3 trained soldiers can hold weapons. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Logout></A>
      <H3>Logout </H3>
      <P>The Logout option on the menu will log you out from World War 2. 
      This is useful if your computer is used by more than one person, to 
      prevent others from accessing your World War 2 account. If you stop 
      using the site for a length of time, you will be automatically logged out 
      anyway - this is to help reduce the load on the extremely busy WW2 
      webserver. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><A 
      name=Messages></A>
      <H3>Messages </H3>
      <P>The Send Message page is accessed from a user's stats page, by clicking 
      on the Send Message button. You are then presented with a page which has 
      areas for you to enter a subject and a message to be sent to that user. 
      </P>
      <P>When someone has sent you a message in this fashion, you will notice 
      the message indicator beneath the main menu will change to show how many 
      new messages you have waiting for you. To read them, simply click on the 
      red number and you will be taken to the Read Messages page. The most 
      recent message will appear at the top of the page, with older messages 
      beneath it in reverse order of receipt. You can use the buttons on the 
      right to Reply to or Delete each message. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="help.php#top">return to top</A> ] </P><BR>&nbsp; <A 
      name=Glossary></A>
      <H2>Glossary </H2>
      <P><B>Age:</B> The length of the game, usually lasting a few months. 
      Between ages, your army size, wealth, weapons will be reset. 
      You will, however, get to keep your officers, and max officer limit. </P>
      <P><B>Armory:</B> The place to purchase weapons. </P>
      <P><B>Army Size:</B> The number of recruits you have. This is the number 
      of people who have clicked your link, plus a fraction of the army size of 
      your officers. Determines the amount of money you get each turn. </P>
      <P><B>Attack:</B> To attack someone, you need to use between 1 and 15 
      attacks. The amount you use determines how much money you get if you win. 
      You get 1 attacks every turn. </P>
      <P><B>Attack Log:</B> A log of everyone who you have attacked recently, 
      and anyone who has attacked you recently. </P>
       <P><B>Upgrades:</B> A place where you can upgrade your stats. </P>
      <P><B>Command Center:</B> Clicking here allows you to view your own stats, 
      including stats that are not available to everyone else. </P>
      <P><B>Casualties:</B> Normal losses suffered in the course of attacking 
      and defending. If your army is not very big, you will probably not suffer 
      very many casualties, if any. </P>
      <P><B>Commander:</B> The person who's page you visited before joining, 
      probably the person who told you about World War 2. </P>
      <P><B>United Kingdom (UK):</B> One of the races/countries in World War 2. United Kindom (UK)get a 25% 
      defence bonus, protecting them when attacked. </P>
      <P><B>Japanese:</B> One of the races/countries in World War 2. Japanese get a 25% 
      covert bonus, making them extremely good spies. </P>
      <P><B>Sheilding Technology:</B> These contribute to the strength of all your 
      defence troops and weaponry. They 
      can be upgraded in the Upgrade page. </P>
      <P><B>Gold:</B> The basic monetary unit of World War 2. Spend gold at 
      the Armory to purchase weapons. </P>
      <P><B>Experience (exp):</B> A monetary unit of World War 2. Spend experience at 
      the upgrade page. Experience is gained through successful attacking and defending </P>
      <P><B>United States (USA):</B> One of the races/countries in World War 2. United States get a 25% 
      income bonus each turn. </P>
      <P><B>Intelligence:</B> A list of other warlords who you have spied on, or 
      who you have intercepted spies from. </P>
      <P><B>Losses:</B> See Casualties </P>
      <P><B>Profile:</B> An in-depth description of a warlord, showing stats 
      useful to know when deciding whether to attack them. </P>
      <P><B>Officer:</B> One of the people who visted your link and decided to 
      join up. They help build your army. </P>
      <P><B>Germans:</B> One of the races/countries in World War 2. Germans have a 25% attack 
      bonus, making them fearsome in battle. </P>
      <P><B>Race/Country:</B> The type of warlord someone is. There are four races/countries: 
      United States, Japanese, United Kindom, and Germans. (note: the use of the word race is not intended to be racistl) </P>
      <P><B>Weapons Technology:</B> This contributes to the overall strength of 
      all your attack troops and weaponry. Can be 
      upgraded in the Upgrade Page. </P>
      <P><B>Turn:</B> The basic unit of time in World War 2. Currently <?=$conf["minutes_per_turn"] ?> 
      minutes long. </P>
      <P><B>Warlord:</B> A character in World War 2. </P>
      <P><B>Weapons:</B> Purchasing weapons increases your attack and defence 
      bonuses, which help you when you attack or defend. </P>
      <P style="TEXT-ALIGN: center">[ <A 
      href="#top">return to top</A> ] </P>
      <?
include ("bottom.php");
?>
        </LI></TD></TR></TBODY></TABLE>
</BODY></HTML>

<? include "gzfooter.php"; ?>